# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-07 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresumes',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userresumes',
            name='name',
        ),
        migrations.AddField(
            model_name='userresumes',
            name='achievements',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='cgpa',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='education',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='hobbies',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='objective',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='pinfo',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='projects',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='userresumes',
            name='skill',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userresumes',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userresumes',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
