# Generated by Django 2.2 on 2020-01-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20170507_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresumes',
            name='achievements',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='userresumes',
            name='education',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userresumes',
            name='hobbies',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='userresumes',
            name='projects',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userresumes',
            name='skill',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
